2021-03-29 18:11:06,568 opmysql.py[line:78] ERROR (1146, "Table 'test_interface.contig_total' doesn't exist")
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\untitled\common\opmysql.py", line 65, in select_one
    rows_affect=self.cur.execute(condition)
  File "D:\python\Lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\python\Lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\python\Lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\python\Lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\python\Lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\python\Lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\python\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\python\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'test_interface.contig_total' doesn't exist")
